mutagen-io/mutagen

.travis.yml
agent/platform.go
appveyor.yml
cmd/mutagen/prompt.go
filesystem/normalize.go
scripts/build.go
session/service.go
session/snapshot.go
ssh/prompt.go
version.go

Go 1.8 brings a lot of goodies that are worth using.  Ideally, I'd like to take advantage of the following:

Update to Go 1.8 features

---

filesystem/atomic.go
filesystem/atomic_posix.go
filesystem/atomic_windows.go
sync/transition.go

Mutagen currently performs staging in a user's home directory on endpoints. But if the target path is not on the same filesystem as the user's home directory on that endpoint, renaming staged files fails with `EXDEV` or similar. This pull request adds a wrapper function that can fall back to a copy-rename-remove-based rename that works across filesystem boundaries.
Fixes #15.

Fix problems with cross-filesystem staging.

---

pkg/generate.go
scripts/build.go
scripts/ci/setup_docker.sh

This ensures that Go.mod is not modified during the build,
and only frozen dependencies are used.
Without this flag, the build is not reproducible.

Add -mod=readonly to build command in scripts/build.go

---

.github/workflows/ci.yml
CONTRIBUTING.md

This commit adds some conservative (but reasonable) build timeouts and fixes permalinks in the CONTRIBUTING.md documentation.

ci: add build timeouts and fix CONTRIBUTING.md permalinks

---

.github/workflows/ci.yml
CONTRIBUTING.md
pkg/synchronization/core/testing_content_test.go
pkg/synchronization/core/transition.go
pkg/synchronization/core/transition_test.go
pkg/synchronization/endpoint/local/endpoint.go

There was a bug (or limitation, at least) in the poll-based watching logic where an externally performed, full inversion of the operations applied by `Transition` could prevent a polling event from being generated if the inversion happened between polling scans.  This was most evident if a new file was propagated to a poll-based watching system and then immediately deleted by the user, but it could happen in more complex scenarios too, so long as the operations performed by `Transition` were fully inverted.  Nothing bad would happen, but the controller wouldn't be notified that a change had occurred (since the poll-based scans wouldn't see any change) until a sync cycle was triggered manually or by some other event.
To fix this, …

sync: trigger event on full inversion with poll-based watching

---

README.md

Hi
Welcome to add link to Mac OS GUI for Mutagen
I have added notarised builds https://github.com/andrewmed/mutagenmon/releases
(tested on different machines, runs without need to unlock in "Security" tab in system preferences)

Add link to MacOS GUI app

---

pkg/filesystem/watching/internal/third_party/winfsnotify/winfsnotify.go
pkg/filesystem/watching/internal/third_party/winfsnotify/winfsnotify_test.go

Here are some small fixes (and a tweak) that I made while testing `winfsnotify` in Docker Desktop. As well as using this code in Mutagen we also use it in the FUSE-based Windows filesharing implementation.
The most interesting one is the fix for long paths (longer than `syscall.MAX_PATH`!) I've added a small test case to demonstrate the issue.
The next one is a handle leak in `removeWatch`. I didn't succeed in making a test case for this unfortunately. For some reason on some machines the leaked handle would prevent a directory being removed and recreated.
The last patch is just to increase the event buffer size to the maximum. I was experiencing quite a lot of event queue overflow so I thought this might be a good idea.

Fixes (and a tweak) to winfsnotify from Docker Desktop

---

pkg/filesystem/watching/internal/third_party/winfsnotify/winfsnotify.go
pkg/filesystem/watching/internal/third_party/winfsnotify/winfsnotify_test.go

This pull request makes some slight tweaks to the winsfsnotify package, adapting it to recent Go runtime and testing changes.  The changes are minimal for now, just enough to make some of the recent long-path fixes work with Go's runtime checks, but a more extensive overhaul (or perhaps minimal, Mutagen-focused rewrite) of this package is still warranted.

sync: winfsnotify updates

---

.github/workflows/ci.yml

This PR disabled GPG key importing and SHA-256 digests for non-release builds. It's needed to allow third-party PRs to build correctly.

ci: disable SHA-256 digests and GPG signing for non-tag builds

---

pkg/filesystem/directory_posix.go
pkg/filesystem/flags_linux.go
pkg/filesystem/flags_posix.go
pkg/filesystem/open_posix.go
pkg/synchronization/core/diff.go
pkg/synchronization/core/entry.go
pkg/synchronization/core/path.go
pkg/synchronization/core/path_test.go
pkg/synchronization/core/reconcile.go
pkg/synchronization/core/scan.go
pkg/synchronization/core/stage.go
pkg/synchronization/core/transition.go
scripts/scan_bench/main.go

This commit adds assorted performance optimizations to the filesystem scanning infrastructure.  It also fixes support for files > 4 GB in size on 32-bit Linux systems.
I think we're reaching the edge of what we can accomplish in Go in terms of scan performance.  Right now, I see a ~25% overhead vs. a comparable `git status` operation for warm scans on the Linux source tree.  Unfortunately, there isn't any more obvious, low-hanging fruit in terms of optimizations in scan, and our CPU profiling seems to indicate that we're syscall-limited.  These numbers and considerations also hold true for cold scans.
On the bright side, that also indicates that scan performance will essentially improve …

sync: add various scan optimizations

---

go.mod
go.sum
pkg/encoding/yaml.go
pkg/filesystem/watching/internal/third_party/notify/event.go
pkg/filesystem/watching/internal/third_party/notify/event_inotify.go
pkg/filesystem/watching/watch_non_recursive_linux.go
pkg/logging/logger.go
pkg/mutagen/licenses.go
pkg/mutagen/licenses_sspl.go
pkg/project/configuration.go

This commit updates golang.org/x dependencies, updates `interface{}` types to `any` for Go 1.18, and makes slight formatting tweaks to license information.

deps: update additional dependencies and code

---

cmd/mutagen-sidecar/main.go
cmd/mutagen/daemon/run.go
cmd/mutagen/sync/list.go
pkg/configuration/forwarding/configuration.go
pkg/configuration/synchronization/configuration.go
pkg/filesystem/temporary.go
pkg/filesystem/watching/watch.go
pkg/filesystem/watching/watch_recursive_windows.go
pkg/forwarding/controller.go
pkg/logging/level.go
pkg/logging/logger.go
pkg/sidecar/paths.go
pkg/sidecar/paths_posix.go
pkg/sidecar/paths_posix_test.go
pkg/sidecar/paths_windows.go
pkg/sidecar/paths_windows_test.go
pkg/stream/valve_writer.go
pkg/synchronization/controller.go
pkg/synchronization/core/scan.go
pkg/synchronization/endpoint/local/endpoint.go
pkg/synchronization/logging.go
sspl/pkg/filesystem/watching/fanotify/watch.go
tools/scan_bench/main.go

This pull request contains an assortment of minor tweaks in preparation for the v0.14.x release series.  The primary focus is on logging and log formatting, but there's also an important optimization to sidecar file staging, correctness enforcement for Compose configuration loading, and a small fix for recursive watch Goroutine termination monitoring in the local endpoint implementation.

all: prepare for v0.14.x

---

pkg/filesystem/watching/watch.go
pkg/filesystem/watching/watch_non_recursive.go
pkg/filesystem/watching/watch_non_recursive_linux.go
pkg/filesystem/watching/watch_non_recursive_unsupported.go
pkg/filesystem/watching/watch_recursive.go
pkg/filesystem/watching/watch_recursive_darwin_cgo.go
pkg/filesystem/watching/watch_recursive_linux_sspl_fanotify.go
pkg/filesystem/watching/watch_recursive_unsupported.go
pkg/filesystem/watching/watch_recursive_windows.go
pkg/filesystem/watching/watch_test.go
pkg/state/coalescer.go
pkg/state/coalescer_test.go
pkg/synchronization/controller.go
pkg/synchronization/core/scan.go
pkg/synchronization/endpoint/local/endpoint.go
sspl/pkg/filesystem/watching/fanotify/fanotify.go
sspl/pkg/filesystem/watching/fanotify/watch.go
tools/watch_demo/watch_demo.go

This commit relocates watch coalescing and event filtering from watcher implementations back into the local synchronization endpoint implementation.  This is something of a "refactored revert" of the original relocation from endpoint to watchers early in the v0.14.x development cycle.  That relocation turned out to be a design mistake, or at a least hindrance, and it's actually easier to manage event coalescing with a slightly different approach that's better suited to adaptation in the face of rapid event notifications and OS-level event overflows.

sync: refactor watch coalescing

---

pkg/agent/dial.go
pkg/mutagen/version.go

This PR restructures error handling on agent handshake failures.  Errors now return as much information as possible to aid in debugging.
#351

agent: restructure error reporting on handshake failure

---

cmd/mutagen/main.go
pkg/mutagen/version.go
pkg/ssh/ssh_windows.go

This PR contains two Windows-related improvements for Mutagen v0.15.0-beta3 (which will hopefully be the last of the v0.15.0 betas).  First, it adds the official Windows OpenSSH binaries to Mutagen's search path.  Second, it simplifies the way that colorized output is enabled for Cobra commands on Windows.

all: Windows improvements for v0.15.0-beta3

---

.github/workflows/ci.yml
images/sidecar/linux/Dockerfile
pkg/synchronization/core/ignore_vcs_mode.go

This PR fixes the unmarshaling behavior of VCS ignore mode types when using the standard library `encoding/json` package.
This PR also replaces the caret syntax that we've been using to pin Go versions with an explicit version specification.
Fixes #358

sync: fix encoding/json unmarshaling of VCS ignore mode type

---

.github/workflows/ci.yml
cmd/mutagen/daemon/start.go
cmd/mutagen/project/flush.go
cmd/mutagen/project/list.go
cmd/mutagen/project/main.go
cmd/mutagen/project/pause.go
cmd/mutagen/project/reset.go
cmd/mutagen/project/resume.go
cmd/mutagen/project/run.go
cmd/mutagen/project/start.go
cmd/mutagen/project/terminate.go
cmd/terminal_windows.go
go.mod
go.sum
images/sidecar/linux/Dockerfile
pkg/docker/docker_darwin.go
pkg/docker/docker_posix.go
pkg/docker/docker_windows.go
pkg/mutagen/version.go
pkg/ssh/ssh_posix.go
pkg/synchronization/core/ignore_vcs_mode.go

This PR backports the following changes for v0.15.1:
- Un-deprecation of projects
- Fix for JSON decoding in `IgnoreVCSMode`
- Change to explicit Go version pinning
Updates #357
Updates #358

all: backport fixes for v0.15.1

---

pkg/forwarding/manager.go
pkg/state/lock_test.go
pkg/state/tracker.go
pkg/state/tracker_test.go
pkg/synchronization/manager.go

The implementation for state.Tracker previously used only condition variables, but this didn't jive with the channel-based context cancellation used with gRPC (and standard HTTP) handlers. To allow for preemption, this commit adds a background Goroutine to state.Tracker to serve as an intermediary between channels and condition variables, allowing for preemptable polling.

state: enable polling preemption for state.Tracker

---

pkg/agent/transport/ssh/transport.go
pkg/process/errors.go

Some POSIX shells (e.g. tcsh) don't return exit codes `126`/`127` when a command isn't found or is invalid. Instead, they return an exit code of `1` and a message such as "command not found". In order to handle these shells, this commit adds a new detection heuristic for POSIX systems based on error output.
Fixes #366

agent: improve command not found detection for some POSIX shells

---

scripts/ci/verify_commits.sh

This PR fixes the `verify_commits.sh` script to account for the fact that we want to allow PR merges into `master` that are not fully up-to-date.

ci: use double dot range spec for rev-list in verify_commits.sh

---

pkg/api/models/forwarding/session.go
pkg/api/models/synchronization/session.go
pkg/forwarding/state.go
pkg/synchronization/state.go

This commit modifies API session representations to always include session status, even if the session is paused. Since the zero value of Status is "disconnected", it's a reasonable interpretation of the session status when paused.

api: always show session status

---

pkg/mutagen/version.go

This commit bumps the development version to v0.16.0-alpha1.  This release is for internal development and testing only; beta and final releases for v0.16.0 will follow shortly.

all: bump version to v0.16.0-alpha1

---

pkg/api/models/synchronization/session.go
pkg/forwarding/manager.go
pkg/forwarding/protocols/docker/protocol.go
pkg/forwarding/protocols/local/protocol.go
pkg/forwarding/protocols/ssh/protocol.go
pkg/logging/logger.go
pkg/stream/line_processor.go
pkg/synchronization/manager.go
pkg/synchronization/protocols/docker/protocol.go
pkg/synchronization/protocols/local/protocol.go
pkg/synchronization/protocols/ssh/protocol.go

This PR makes minor changes to logging, comments, and errors in preparation for v0.16.  Most of these changes have no visible impact to users.
The only user-visible change is that the `successfulCycles` field for synchronization sessions will now be rendered unconditionally in JSON output, even if it's `0`.

all: minor comment, logging, error, and output tweaks for v0.16

---

pkg/api/models/synchronization/session.go
pkg/housekeeping/housekeep.go

This PR switches synchronization housekeeping to use inactivity periods of one week (instead of 30 days) when classifying session caches and staging roots as stale.
This PR also reverts an unreleased prior change to synchronization JSON output.

sync: use shorter inactivity periods for cache and staging housekeeping

---

pkg/synchronization/core/scan.go
pkg/synchronization/core/scan_test.go
pkg/synchronization/core/testing_entries_test.go

This PR modifies scan operations to flag non-UTF-8 filenames as problematic content (with sanitized names) instead of passing them through to the content map with a "bag-of-bytes" mentality.  While we would ideally be able to treat them opaquely, doing so unfortunately leads to somewhat useless name comparisons.  Moreover, Protocol Buffers can't marshal non-UTF-8 strings.
The effect of this change should be minimal.  It shouldn't affect any cases that weren't previously affected by Protocol Buffers encoding failing.
This addresses an issue reported on Slack by @rfay.

sync: flag non-UTF-8 filenames as problematic content

---

cmd/mutagen/sync/list_monitor_common.go
pkg/api/models/synchronization/configuration_test.go
pkg/mutagen/version.go
pkg/synchronization/configuration.go

This PR adds a few bits of missing logic for the new permissions mode functionality.  It also bumps the version to v0.16.0-alpha3.

sync: add missing logic for permissions mode

---

cmd/mutagen/sync/create.go

This PR adds what is (hopefully) the last of the CLI configuration wiring for the new permissions mode option. 🤯

sync: wire permissions mode into the combined CLI configuration

---

.github/workflows/ci.yml
images/sidecar/linux/Dockerfile
pkg/mutagen/version.go
pkg/synchronization/core/scan.go
pkg/synchronization/core/scan_test.go
pkg/synchronization/core/testing_entries_test.go

This PR backports selective fixes for the v0.15.3 release, including:
- bcea8e7 and 8864b22
This PR addresses a behavioral issue with non-Unicode filenames reported by @rfay on Slack.

all: v0.15.3 backports

---

.github/workflows/ci.yml
images/sidecar/linux/Dockerfile
pkg/mutagen/version.go
pkg/synchronization/core/scan.go

This pull request fixes a corner case in accelerated scanning with `fanotify`.  Specifically, it fixes the case where an empty directory is deleted and a directory with the same name is quickly renamed into its place with different contents.  This case is problematic for `fanotify` since the API only reports the parent directory path for these types of operations.  This also occurs with files or symbolic links, but we always explicitly recheck those since we pay for their metadata anyway.
To fix this corner case, we use a simple additional heuristic on Linux: we consider directories to be "dirty" if they are either explicitly marked as dirty or if their immediate parent is marked as dirty.  This does have some minor performance …

sync: fix accelerated scanning corner case for fanotify

---

scripts/ci/test_386.sh

This PR disables Docker integration tests for the 386 architecture.  GitHub has switched their runners from Docker EE to Docker CE and they are no longer shipping 386 Docker binaries, at least on Windows (and likely other platforms soon).

ci: disable Docker integration tests on 386

---

scripts/ci/test_386.sh

This PR backports #389 to the v0.15.x release branch.  This is necessary to continue building v0.15.x releases due to a recent change to GitHub Actions runners.

ci: disable Docker integration tests on 386 (backport)

---

.github/workflows/ci.yml
pkg/mutagen/version.go

This PR bumps the version to v0.16.0.  There are no changes from v0.16.0-rc1.

all: bump version to v0.16.0

---

.github/workflows/ci.yml
images/sidecar/linux/Dockerfile

This PR updates the Go build version to 1.19.3, which includes a fix for CVE-2022-41716.  This CVE doesn't have any significant impact on Mutagen, but is worth updating anyway since we're going to ship an updated Mutagen Compose release.

deps: update to Go 1.19.3

---

.github/workflows/ci.yml
images/sidecar/linux/Dockerfile
pkg/mutagen/version.go

This PR backports the update to Go 1.19.3.

deps: update to Go 1.19.3 (backport)

---

pkg/filesystem/resources.go

This pull request is need to fix resolving symlinks with an absolute path. These kind of symlinks are used heavily by nix. Therefore I've encountered problems in finding the agent bundle on nix-darwin.
It resolves issue #400 , which also contains a more detailed analysis of the problem.

fs: fix resolving absolute symlinks

---

pkg/filesystem/watching/internal/third_party/notify/watcher_inotify.go
pkg/mutagen/version.go

This PR modifies the vendored inotify watcher implementation to allow for event dropping.  At the moment, no events are dropped, which can block the watcher's run loop from signaling termination.  Since our non-recursive watching is opportunistic/best-effort anyway (i.e. only meant to reduce sync cycle latency, not responsible for tracking changes), there's no harm in this change.  Without this, the watcher can block endpoint shutdown indefinitely if the event queue is full.
Eventually, we'll probably just want to write our own inotify implementation. Our needs are simpler than those of the code that we've vendored, which also no longer appears to be maintained upstream.
No …

watch: allow internal inotify watcher to drop events

---

pkg/filesystem/resources.go
pkg/filesystem/watching/internal/third_party/notify/watcher_inotify.go
pkg/mutagen/version.go

This PR backports two fixes for the v0.16.x release branch, in particular:
- A fix for resolution of absolute symlinks when identifying `libexec` paths (thanks to @dj95)
- A fix for inotify event channel blocking on endpoint shutdown
Backports the fix for #400

all: v0.16.2 backports

---

.github/workflows/ci.yml
images/sidecar/linux/Dockerfile
pkg/mutagen/version.go

This PR updates the underlying Go version to 1.19.4.

V0163 backports

---

cmd/mutagen/forward/create.go
cmd/mutagen/sync/create.go

This commit modifies the create commands (for both synchronization and forwarding) to accept multiple specifications of the -c/--configuration-file flag, merging later specifications on top of earlier ones.
#406

cmd: allow multiple default configuration files to be specified

---

pkg/agent/bundle.go
scripts/build.go

This PR switches the build script and agent extraction code to use the faster gzip implementation included in the new compress package that we added during staging optimization.

all: switch to faster gzip implementation for agent bundle handling

---

pkg/extension/doc.go
pkg/extension/environment.go
pkg/url/url.go

This PR adds a mechanism to tweak behaviors when running in the Mutagen Extension for Docker Desktop.
The primary tweak required here is a change to URL validation behavior, but others may be necessary in the future.

all: add mechanism to detect extension environment

---

pkg/extension/doc.go
pkg/extension/environment.go
pkg/url/url.go

This PR backports the #420 to the v0.16.x release branch.
This isn't critical at the moment because this patch is only for the Docker Desktop extension, but it's best to have it ready to go if/when v0.16.5 ships.

all: backport mechanism to detect extension environment

---

.github/workflows/ci.yml
images/sidecar/linux/Dockerfile

This PR updates the build toolchain to Go 1.20.  It also updates the sidecar base image to Alpine 3.17, which should have been done earlier, at least for the development branch.
Unlike previous toolchain updates, we're going to continue supporting and testing the previous Go version.  This is a bit of an experiment, but it shouldn't present any significant difficulty.  The benefits (namely portability and flexibility) should outweigh the costs (i.e. waiting to adopt new APIs or managing their adoption through build tags).

deps: update to Go 1.20

---

.github/workflows/ci.yml
images/sidecar/linux/Dockerfile
pkg/mutagen/version.go

This PR updates Go to 1.19.6 and makes a corresponding update to the sidecar's Alpine base image to match the build image Alpine version.
There are [a number of bugfixes](https://github.com/golang/go/issues?q=milestone%3AGo1.19.6+label%3ACherryPickApproved) brought in by Go 1.19.6, including a few CVE fixes (though none appear to impact Mutagen).

all: prepare for v0.16.5 release

---

LICENSE
cmd/mutagen/sync/list_monitor_common.go
pkg/mutagen/version.go

This PR bumps the version to v0.17.0 and makes a clarification to the `LICENSE` file.
It also modifies synchronization session listings to hide compression algorithm information for local endpoints (where compression isn't used).

all: prepare for v0.17.0 release

---

.github/workflows/ci.yml
images/sidecar/linux/Dockerfile

This PR updates the Go versions being used to 1.20.3 and 1.19.8.
There are a number of compiler and runtime bugs fixed by these releases. There are also a few CVEs fixed in these releases, but none that affect Mutagen's use of Go.

deps: update Go versions to 1.20.3 and 1.19.8

---

scripts/ci/analyze.sh
scripts/ci/notarize.sh
scripts/ci/verify_commits.sh

This PR adds an additional CI check to ensure that `go.mod` and `go.sum` are up-to-date (as defined by `go mod tidy`).  This is as important as a `go fmt` check.
This PR also normalizes writing of CI error messages to standard error.

ci: ensure that go mod tidy doesn't cause changes

---

pkg/housekeeping/housekeep.go

This PR causes agent housekeeping to be skipped in Mutagen sidecar containers.
Mutagen sidecar containers are typically unpacked via OverlayFS onto an ext4 filesystem with either relatime or noatime. In the case of an older sidecar image, this could result in the agent binary actually unlinking itself, which won't prevent it from functioning, but which will require reinstallation by the next session targeting the container (in which case the `fanotify` support of the built-in agent will typically be lost).

all: don't housekeep agents inside Mutagen sidecar containers

---

.github/workflows/ci.yml
images/sidecar/linux/Dockerfile

This PR updates the Go versions used for builds and testing to 1.20.4 and 1.19.9.

deps: update Go versions to 1.20.4 and 1.19.9

---

.github/workflows/ci.yml
cmd/mutagen/common/templating/templating.go
cmd/mutagen/forward/list_monitor_common.go
cmd/mutagen/forward/monitor.go
cmd/mutagen/project/common_windows.go
cmd/mutagen/sync/list_monitor_common.go
cmd/mutagen/sync/monitor.go
images/sidecar/linux/Dockerfile
pkg/agent/dial.go
pkg/logging/logger.go
pkg/mutagen/version.go
pkg/platform/terminal/doc.go
pkg/platform/terminal/neutralization.go

This PR backports updates and fixes for v0.16.6.  More information will be available in the associated release notes.

all: backport changes for v0.16.6

---

cmd/mutagen/common/templating/templating.go
cmd/mutagen/forward/list_monitor_common.go
cmd/mutagen/forward/monitor.go
cmd/mutagen/sync/list_monitor_common.go
cmd/mutagen/sync/monitor.go
pkg/agent/dial.go
pkg/logging/logger.go
pkg/platform/terminal/doc.go
pkg/platform/terminal/neutralization.go
pkg/process/errors.go

This PR adds neutralization (escaping) of control characters in terminal output for values that aren't locally controlled. This output (if unsanitized) could cause terminal corruption. In theory, it could also be used as an attack vector for intentionally causing terminal corruption when synchronizing with an untrusted (and malicious) remote. On very old terminal emulators, it can theoretically be used as an attack vector for code execution (see, for example, CVE-2003-0069), though this type of vulnerability has been patched for over 20 years.
We still treat the daemon as a trusted entity (since it is under user control) and don't sanitize (most) output under its control (such as locally generated error messages).
We intentionally …

cli: neutralize control characters in terminal output

---

.github/workflows/ci.yml
go.mod
go.sum
images/sidecar/linux/Dockerfile

This PR updates the following dependencies:
- Go to 1.20.5 and 1.19.10
- These contain a fix for CVE-2023-29403, which could affect users in the (unlikely) event that they're using Mutagen with `setuid`/`setgid`
- Alpine Linux to 3.18
- github.com/mutagen-io/fsevents
- This contains a fix for a symbol collision issue with the upstream github.com/fsnotify/fsevents

deps: update Go, Alpine, and fsevents dependencies

---

.github/workflows/ci.yml
go.mod
go.sum
images/sidecar/linux/Dockerfile
pkg/mutagen/version.go

This PR backports updates to the v0.17.x release branch in preparation for the v0.17.2 release.  In particular, it:
- Updates Go to 1.20.5 and 1.19.10 
- These contain a fix for CVE-2023-29403, which could affect users in the (unlikely) event that they're using Mutagen with `setuid`/`setgid`
- Updates github.com/mutagen-io/fsevents
- This contains a fix for a symbol collision issue with the upstream github.com/fsnotify/fsevents
- Bumps the release version to v0.17.2
This should help unblock mutagen-io/mutagen-compose#64.

all: prepare for v0.17.2 release

---

.github/workflows/ci.yml
images/sidecar/linux/Dockerfile
pkg/mutagen/version.go

This PR updates the Go dependency to 1.20.12 and bumps the version to v0.17.4.

all: prepare for v0.17.4 release

---

.github/workflows/ci.yml
scripts/ci/setup_partitions_windows_template.txt

This PR fixes Windows CI partitioning to work in mirrors of the repo with different names.

ci: make Windows partition setup to mirrors with different names

---

pkg/forwarding/state.go
pkg/forwarding/state_test.go
pkg/synchronization/core/entry.go
pkg/synchronization/core/entry_test.go
pkg/synchronization/state.go
pkg/synchronization/state_test.go

This PR ensures all types in `pkg/api/models` implement JSON decoding.
We want these types to be able to decode incoming JSON, but there were a few enumeration types that didn't implement `UnmarshalText` (implicitly or otherwise).

api: ensure all enumeration types implement UnmarshalText

---

.github/workflows/ci.yml

This PR modifies the CI setup so that only the canonical repository attempts to push a sidecar image. This is to stop forks (which don't have the necessary secrets) from erroring out in the relevant actions.

ci: only attempt to push sidecar image from canonical repository

---

.github/workflows/ci.yml
images/sidecar/linux/Dockerfile
pkg/agent/transport/docker/transport.go
scripts/ci/docker/linux/Dockerfile

This PR fixes an issue with error code detection for Moby v28, which now delineates "command not found" into the proper 127 exit code.
https://github.com/ddev/ddev/issues/7015
This PR also updates Go and Alpine dependencies.
A backport will be required for a v0.18.1 release.
CC @rfay

docker: handle new error code delineation in Moby v28+
