- .github/workflows/ci.yml
- images/sidecar/linux/Dockerfile
- scripts/ci/analyze.sh
- scripts/ci/commitlint/config.json
- scripts/ci/setup_docker.sh
- scripts/ci/setup_go.sh
- scripts/ci/verify.sh
Mutagen is going to switch to a GitHub flow model for development, both to keep development a bit more organized and to allow for easier acceptance of third-party pull requests.  To facilitate this transition, this pull request adds a number of automated checks to the CI pipeline to reduce the burden on pull request reviewers.
> ci: add validations in preparation for pull requests

- .github/pull_request_template.md
- CONTRIBUTING.md
- DCO
This pull request updates contributing guidelines for pull requests.
> docs: update pull request guidelines

- cmd/mutagen-agent/main.go
- cmd/mutagen-sidecar/main.go
- cmd/mutagen/main.go
spf13/cobra gives the --version flag for free... and I keep wanting it and trying to use it. Most command-line tools provide it. So here it is :)
> Add --version flag for mutagen

- LICENSE
- cmd/mutagen-agent/synchronizer.go
- pkg/docker/docker.go
- pkg/forwarding/endpoint/local/dialer.go
- pkg/ipc/ipc_posix.go
- pkg/ipc/ipc_windows.go
- pkg/service/daemon/server.go
- pkg/ssh/ssh.go
- pkg/synchronization/core/scan_test.go
- pkg/synchronization/core/transition_test.go
- pkg/synchronization/endpoint/local/endpoint.go
- sspl/pkg/filesystem/watching/fanotify/doc.go
- sspl/pkg/filesystem/watching/fanotify/fanotify.go
- sspl/pkg/filesystem/watching/fanotify/fanotify_test.go
- sspl/pkg/filesystem/watching/fanotify/watch.go
- sspl/pkg/filesystem/watching/fanotify/watch_test.go
- sspl/pkg/platform/linux/capabilities.go
- sspl/pkg/platform/linux/capabilities_test.go
- sspl/pkg/platform/linux/doc.go
- sspl/pkg/platform/linux/version.go
- sspl/pkg/platform/linux/version_test.go
This pull request contains no functional changes, only formatting changes for consistency and variable renames designed to make older context-related code more idiomatic.
> all: minor formatting changes and variable renames

- pkg/mutagen/version.go
This pull requests updates the version to v0.14.0 in preparation for its final release.
> all: bump version to v0.14.0

- cmd/mutagen/project/flush.go
- cmd/mutagen/project/list.go
- cmd/mutagen/project/main.go
- cmd/mutagen/project/pause.go
- cmd/mutagen/project/reset.go
- cmd/mutagen/project/resume.go
- cmd/mutagen/project/run.go
- cmd/mutagen/project/start.go
- cmd/mutagen/project/terminate.go
- pkg/api/models/forwarding/endpoint.go
- pkg/api/models/synchronization/endpoint.go
- pkg/mutagen/version.go
This PR makes final adjustments in preparation for the v0.15.0 release.
The most notable is the deprecation of Mutagen's project functionality, which hasn't seen any functionality updates in quite some time and is somewhat too design-locked to evolve further.  There's no removal date set in stone yet.  It's also possible that it could be maintained externally to Mutagen (using the same APIs as Mutagen Compose), but unless there's a significant demand for that (as well as some interest in maintaining the code) from the community, it'll likely be removed with Mutagen v0.17.
> all: final adjustments for v0.15.0

- cmd/mutagen/project/flush.go
- cmd/mutagen/project/list.go
- cmd/mutagen/project/main.go
- cmd/mutagen/project/pause.go
- cmd/mutagen/project/reset.go
- cmd/mutagen/project/resume.go
- cmd/mutagen/project/run.go
- cmd/mutagen/project/start.go
- cmd/mutagen/project/terminate.go
This PR reverts the deprecation of projects.  It turns out that a large number of people are still using this functionality.
Updates #357.
This should be backported for v0.15.1.
> projects: undeprecate projects

- cmd/mutagen-agent/forwarder.go
- cmd/mutagen-agent/main.go
- cmd/mutagen-agent/synchronizer.go
- cmd/mutagen-sidecar/main.go
- cmd/mutagen/daemon/run.go
- cmd/mutagen/main.go
This commit makes some minor adjustments to Cobra and CLI related code. The biggest change is hiding the default completion command that was added with Cobra 1.2.0.  Other changes are purely cosmetic.
> cli: add various Cobra fixes and adjustments

- pkg/agent/transport/docker/transport.go
- pkg/agent/transport/ssh/transport.go
- pkg/state/marker.go
- scripts/build.go
This commit updates Mutagen to take advantage of Go 1.19 features.
> all: update code for Go 1.19

- pkg/agent/transport/ssh/transport.go
- pkg/api/models/forwarding/session.go
- pkg/api/models/synchronization/session.go
- pkg/forwarding/state.go
- pkg/mutagen/version.go
- pkg/process/errors.go
- pkg/synchronization/core/transition.go
- pkg/synchronization/state.go
This PR backports selective fixes for the v0.15.2 release, including:
- (Portions of) 98c5622
- ee58b6a
- 3b6e23a
#366
> all: v0.15.2 backports

- .github/issue_template.md
- .github/pull_request_template.md
- .github/workflows/ci.yml
- images/sidecar/linux/Dockerfile
- pkg/mutagen/version.go
- pkg/state/tracker.go
- pkg/synchronization/core/permissions.go
- pkg/synchronization/core/permissions_mode_test.go
- pkg/synchronization/core/scan.go
- pkg/synchronization/core/scan_test.go
- pkg/synchronization/core/transition.go
This PR contains an assortment of minor comment, formatting, documentation, test, and CI changes in preparation for v0.16.0-beta1.  There are no changes to visible functionality other than a different format for non-UTF-8 filenames.
> all: prepare for v0.16.0-beta1

- pkg/synchronization/core/scan.go
This PR optimizes the heuristic added in #385, reducing the performance penalty for this fix to effectively zero.
> sync: optimize fanotify edge case heuristic

- pkg/mutagen/version.go
- pkg/synchronization/core/scan.go
This PR backports the `fanotify` edge case fixes in #385 and #387.
> all: v0.15.4 backports

- pkg/mutagen/version.go
This PR updates the version in preparation for the v0.16.4 release.
> all: prepare for v0.16.4 release

- cmd/mutagen/daemon/run.go
- pkg/agent/transport/docker/transport.go
- pkg/mutagen/version.go
- pkg/process/errors.go
This PR attempts to identify a few common errors and present them in a more user-friendly manner.
In particular, it attempts to identify:
- Containers not existing
- Containers being stopped
- Stale daemon endpoints being unremovable
Many, both on the issue tracker and in the Slack workspace.  This is Mutagen's failing, not that of the users.
There may be other common cases that users encounter that present very opaque errors.  If anyone wants to comment on this PR with additional errors, I'm happy to work on making those clearer.
> cli: improve error UX in common cases

- pkg/agent/transport/ssh/transport.go
Much like with our Docker transport, we were missing an opportunity to capture some SSH error outputs that might be useful in debugging. In particular, we can capture the error output of `scp` and return that to the user, which might clarify errors that are masked by `ClassifyError`.
> ssh: improve error UX

- .github/workflows/ci.yml
- cmd/mutagen/common/templating/templating.go
- cmd/mutagen/daemon/run.go
- cmd/mutagen/forward/list_monitor_common.go
- cmd/mutagen/forward/monitor.go
- cmd/mutagen/project/common_windows.go
- cmd/mutagen/sync/list_monitor_common.go
- cmd/mutagen/sync/monitor.go
- images/sidecar/linux/Dockerfile
- pkg/agent/dial.go
- pkg/agent/transport/docker/transport.go
- pkg/agent/transport/ssh/transport.go
- pkg/housekeeping/housekeep.go
- pkg/logging/logger.go
- pkg/mutagen/version.go
- pkg/platform/terminal/doc.go
- pkg/platform/terminal/neutralization.go
- pkg/process/errors.go
This PR backports updates and fixes for v0.17.1.  More information will be available in the associated release notes.
> all: backport changes for v0.17.1

- cmd/mutagen/project/common_windows.go
This PR improves shell resolution in Mutagen projects on Windows.
GHSA-fwj4-72fm-c93g
> cli: improve validation during Windows shell resolution in projects

- tools/scan_bench/digest_nosspl.go
- tools/scan_bench/digest_sspl.go
- tools/scan_bench/main.go
This PR fixes handling (and improves parsing) of the `-d`/`--digest` flag in `scan_bench`.
> tools: fix digest flag in scan_bench and improve its parsing

- .github/workflows/ci.yml
- images/sidecar/linux/Dockerfile
- pkg/mutagen/version.go
This PR will include the final updates for v0.18.0-beta1.  It is still pending.
> all: prepare for v0.18.0-beta1 release

- .github/workflows/ci.yml
- pkg/mutagen/version.go
This PR fixes breakage introduced with v0.18.0-rc2 where the sidecar image wasn't pushed on release.
It also bumps the version to v0.18.0-rc3 since we'll need another tagged release.
> ci: fix push condition for sidecar image

- pkg/mutagen/version.go
This PR bumps the version to v0.18.0 in preparation for the final release.
> all: bump version to v0.18.0

- README.md
- SECURITY.md
This PR updates the security contact email address.
> docs: update security contact email

- .github/workflows/ci.yml
- images/sidecar/linux/Dockerfile
- pkg/agent/transport/docker/transport.go
- scripts/ci/docker/linux/Dockerfile
This PR backports mutagen-io/mutagen#523 to the v0.18.x release branch.
https://github.com/ddev/ddev/issues/7015
This PR also updates Go and Alpine dependencies.
CC @rfay
> all: backport Docker transport fix in mutagen-io/mutagen#523
